[workspace]
members = [
    "rusty_ai",
]
exclude = ["benchmarks", "examples"]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
rusty_ai = { path="./rusty_ai" }
rand = "0.8.5"
itertools = "0.10.5"
