[package]
name = "mnist_nllloss"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_ai.workspace = true
rand.workspace = true
load_mnist = { version = "0.5.0", package = "mnist" }
