[package]
name = "mnist_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
load_mnist = { version = "0.5.0", package = "mnist" }
rusty_ai = { path = "../.." }
