[package]
name = "benches"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_ai = { path = "../rusty_ai" }
rand = "0.8.5"
