[package]
name = "benches"
version.workspace = true
edition.workspace = true
publish = false

[dev-dependencies]
rusty_ai = { path = "../rusty_ai" }

[[bench]]
name = "example_bench"
path = "./example_bench.rs"
